### ISSUE TITLE
Unable to connect to device with Laravel 5.8

### ISSUE THREAD

**Issue by hmorv** [jjsquady/mikrotikapi#4]
Hi,

Just trying your Api wrapper in a brand new 5.8 Laravel installation.

Followed the steps from the readme but unable to make it work?

Just created a controller:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mikrotik;

class MikrotikTestController extends Controller
{

    public function index()
    {
        $conn = Mikrotik::connect(['192.168.50.67', 'admin', '']);
        if ($conn->isConnected()) {
            dd('ok');
        }
            $iComm = new InterfaceCommand($conn);
            $interfaces = $iComm->all();dd($interfaces);
    }
}
```

But output throws: 

>  Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method jjsquady\MikrotikApi\Core\Client::isConnected()

Idk if maybe I'm missing something? Tried using the Facade with same result.

**Comment by mmeidyfachreza** [comment]
same problem with laravel 5.8

**Comment by jjsquady** [comment]
Hi guys!

Sorry for delay to respond. I make some changes to make compatible with 5.8... the tests its covering the early phase of this development. Tested with a RB hAP ac2 with 6.44.3 firmware.

At moment only listing interfaces... I try to spend more time on this project.

Thanks!
